### ISSUE TITLE
Application Crash on Startup after Elite Dangerous Update 13

### ISSUE THREAD

**Issue by psolem** [Yori-Mirano/elite-dangerous-route-widget#11]
The application crashes when it is opened. 

I would like to help with the development on this app but not sure how to get started.

![edrw startup errror](https://user-images.githubusercontent.com/79765379/187041246-eda6fd95-769d-49ec-a64b-d3b65e8508ea.png)

**Comment by Yori-Mirano** [comment]
Thanks for reporting the bug. Sorry for the delay in my response. This should be fixed with 1.0.0-alpha.5.2 version I just pushed. Please let me know if this is the case for you.
