### ISSUE TITLE
"True Vertical" layout

### ISSUE THREAD

**Issue by parduz** [Yori-Mirano/elite-dangerous-route-widget#2]
Please, implement a "true vertical" layout, with a vertical line and stars moving up and down, which can be aligned on one of the sides of the screen, which the game does not use (and are even more empty for players that uses a wider FOV).

Also, please explain how to use it over the game window, for the ppl that does'nt capture video.

Thanks :)

**Comment by Yori-Mirano** [comment]
**Vertical layout** added to the alpha.2 release:
https://github.com/Yori-Mirano/elite-dangerous-route-widget/releases/tag/v1.0.0-alpha.2

![vertical-layout](https://user-images.githubusercontent.com/1879222/119235701-221dbd80-bb34-11eb-93a5-3415409c4b29.png)

The alpha 1 introduced the **ability to display the widget over the game** without OBS. But the constraint is to have to configure the display of the game in borderless windowed. 
However, I have noticed that the widget can sometimes get behind the game. I haven't figured out how to fix this yet. I try to fix this as soon as I find a solution.
